version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"
    REPOSITORY_URI: "864981742651.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - >
        aws ecr get-login-password --region ap-south-1 |
        docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Setting up kubeconfig for EKS...
      - aws eks update-kubeconfig --region ap-south-1 --name brain-cluster

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Updating Kubernetes deployment YAML..."
      - sed -i "s|image:.*|image: $REPOSITORY_URI:$IMAGE_TAG|" deployment.yaml

  post_build:
    commands:
      - echo "Applying Kubernetes deployment..."
      - kubectl apply -f deployment.yaml
      - echo "Build and deploy complete."
