version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 864981742651.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=864981742651.dkr.ecr.ap-south-1.amazonaws.com/brain-tasks-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Setting up kubeconfig for EKS...
      - aws eks update-kubeconfig --region ap-south-1 --name brain-cluster --alias brain-cluster
      - export KUBECONFIG=$HOME/.kube/config

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Updating deployment.yaml with image tag...
      - 'sed -i "s|image: .*|image: $REPOSITORY_URI:$IMAGE_TAG|" deployment.yaml'
      - echo Applying Kubernetes manifests...
      - kubectl apply -f deployment.yaml --validate=false
      - echo Deployment to EKS complete.
      - echo Testing kubectl connection...
      - kubectl get nodes || echo "kubectl get nodes failed — check IAM role mapping"

artifacts:
  files:
    - deployment.yaml
