version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing kubectl..."
      - |
        KUBECTL_VERSION=$(curl -s https://dl.k8s.io/release/stable.txt)
        curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
        chmod +x kubectl
        mv kubectl /usr/local/bin/
        kubectl version --client

      - echo "Installing AWS CLI..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - ./aws/install --update
      - aws --version

  pre_build:
    commands:
      - echo "Updating kubeconfig for EKS..."
      - aws eks update-kubeconfig --region ap-south-1 --name brain-cluster

  build:
    commands:
      - echo "Deploying to EKS..."
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
